import React, { FC } from 'react';
import { Button } from '../../../../components/Button/V2/Button';
import * as S from './S.el';

type Props = {
  title: string;
  btnText?: string;
  onClick?: () => void;
  withoutBtn?: boolean;
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
  userRating?: string;
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
  styles?: Object;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> task/2675
};

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
export const Heading: FC<Props> = ({ title, onClick, btnText, withoutBtn, userRating }: Props) => {
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
export const Heading: FC<Props> = ({ title, onClick, btnText, withoutBtn, styles }: Props) => {
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> task/2675
  return (
    <S.Container style={styles && styles}>
      <S.Title>{title}</S.Title>
      {!withoutBtn && (
        <Button primary onClick={onClick}>
          {btnText}
        </Button>
      )}
      {
        userRating &&
        <S.RateText>
          {userRating}
        </S.RateText>
      }
    </S.Container>
  );
};
